"""Generate the CSS utilities the vendored Tailwind build is missing.

static/css/tailwind.css is a vendored Tailwind artifact. Tailwind emits only the
utilities it saw when it ran, so any class added to a template afterwards -- or
any class living inside a JavaScript template string, which its scanner never
sees -- silently resolves to nothing. No error, no warning: the element just
renders unstyled. That is how the EGRESS badge ended up transparent.

Regenerating with the real Tailwind CLI needs Node and a package download, which
is not available in an airgapped build. But the vendored artifact already ships
every design token (286 --color-* variables, --spacing, --radius-*); only the
utility *rules* were dropped. Those rules are mechanical, so this command
rebuilds the missing ones from the tokens already present.

    python manage.py build_css            # rewrite the generated stylesheet
    python manage.py build_css --check    # fail if it is stale or incomplete

--check is the important half: it turns a silent styling failure into a build
failure. Run it in the image build, next to collectstatic.

Anything this command cannot express is reported rather than skipped, so an
unsupported class is a loud error and never a mystery at runtime.
"""
import re
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

GENERATED = 'css/utilities.generated.css'

HEADER = """/* GENERATED by `python manage.py build_css` -- do not edit by hand.
 *
 * Utilities missing from the vendored static/css/tailwind.css, rebuilt from the
 * design tokens that file already defines. Loaded after it, so these win.
 *
 * Add a class to a template, re-run the command, commit the result.
 */
@layer utilities {
"""

# Utility patterns this project actually uses. Each maps a class name to the
# declarations it produces. Deliberately not a complete Tailwind implementation:
# an unmatched class is an error, not a silent no-op.
COLOR_PROPERTIES = {
    'bg': 'background-color',
    'text': 'color',
    'border': 'border-color',
    'ring': '--tw-ring-color',
    'from': '--tw-gradient-from',
    'to': '--tw-gradient-to',
}

SPACING_PROPERTIES = {
    'p': ['padding'], 'px': ['padding-inline'], 'py': ['padding-block'],
    'pt': ['padding-top'], 'pb': ['padding-bottom'],
    'pl': ['padding-inline-start'], 'pr': ['padding-inline-end'],
    'm': ['margin'], 'mx': ['margin-inline'], 'my': ['margin-block'],
    'mt': ['margin-top'], 'mb': ['margin-bottom'],
    'ml': ['margin-inline-start'], 'mr': ['margin-inline-end'],
    'gap': ['gap'], 'w': ['width'], 'h': ['height'],
}

BORDER_WIDTH = {
    'border': ['border-width'], 'border-x': ['border-inline-width'],
    'border-y': ['border-block-width'], 'border-t': ['border-top-width'],
    'border-b': ['border-bottom-width'],
    'border-l': ['border-inline-start-width'], 'border-r': ['border-inline-end-width'],
}

VARIANTS = {
    'hover': '&:hover { @media (hover: hover) { %s } }',
    'focus': '&:focus { %s }',
    'group-hover': '&:is(:where(.group):hover *) { @media (hover: hover) { %s } }',
    'disabled': '&:disabled { %s }',
}


def escape(cls):
    """Tailwind's CSS-selector escaping for characters that are not name-safe."""
    return ''.join('\\' + ch if ch in '!:/[]().%,#' else ch for ch in cls)


class Compiler:
    def __init__(self, tokens):
        self.tokens = tokens

    def declarations(self, base):
        """CSS declarations for a bare utility, or None if unsupported."""
        # arbitrary value: bg-[#0f172a], text-[10px], h-[42px]
        arbitrary = re.fullmatch(r'([a-z-]+)-\[([^\]]+)\]', base)
        if arbitrary:
            prefix, value = arbitrary.groups()
            is_length = bool(re.fullmatch(r'-?[\d.]+(px|rem|em|%|vh|vw)', value))
            # `text` is overloaded: text-[10px] is a size, text-[#fff] a colour.
            if prefix == 'text':
                return f'font-size: {value};' if is_length else f'color: {value};'
            if prefix in COLOR_PROPERTIES and not is_length:
                return f'{COLOR_PROPERTIES[prefix]}: {value};'
            if prefix in SPACING_PROPERTIES:
                return ' '.join(f'{p}: {value};' for p in SPACING_PROPERTIES[prefix])
            return None

        # colour, optionally with an alpha suffix: bg-teal-50, bg-white/20
        colour = re.fullmatch(r'([a-z]+)-([a-z]+(?:-\d+)?)(?:/(\d+))?', base)
        if colour:
            prefix, name, alpha = colour.groups()
            prop = COLOR_PROPERTIES.get(prefix)
            token = f'--color-{name}'
            if prop and token in self.tokens:
                if alpha:
                    return f'{prop}: color-mix(in oklab, var({token}) {alpha}%, transparent);'
                return f'{prop}: var({token});'

        # border width: border-x-0
        width = re.fullmatch(r'(border(?:-[xytblr])?)-(\d+)', base)
        if width and width.group(1) in BORDER_WIDTH:
            props = BORDER_WIDTH[width.group(1)]
            return ' '.join(f'{p}: {width.group(2)}px;' for p in props)

        # spacing on the --spacing scale, possibly negative: px-2, -mt-0.5
        spacing = re.fullmatch(r'(-?)([a-z]{1,2})-(\d+(?:\.\d+)?)', base)
        if spacing:
            sign, prefix, amount = spacing.groups()
            props = SPACING_PROPERTIES.get(prefix)
            if props:
                value = f'calc(var(--spacing) * {sign}{amount})'
                return ' '.join(f'{p}: {value};' for p in props)

        return None

    def rule(self, cls):
        """Full CSS rule for a class, or None if it cannot be expressed."""
        important = cls.startswith('!')
        base = cls[1:] if important else cls

        variant = None
        if ':' in base:
            variant, base = base.rsplit(':', 1)
            if variant not in VARIANTS:
                return None

        declarations = self.declarations(base)
        if declarations is None:
            return None
        if important:
            declarations = re.sub(r';', ' !important;', declarations)

        body = VARIANTS[variant] % declarations if variant else declarations
        return f'  .{escape(cls)} {{ {body} }}'


def extract_classes(paths):
    """Class names referenced by templates and scripts.

    Reads static class="..." attributes and the string literals inside dynamic
    :class="[...]" bindings, which is where the JS-only classes hide.
    """
    found = {}
    attribute = re.compile(r'(?:^|\s):?class="([^"]*)"', re.S)
    literal = re.compile(r"'([^']*)'")

    for path in paths:
        text = path.read_text(encoding='utf-8')
        chunks = [m.group(1) for m in attribute.finditer(text)]
        # JS builds class lists inside backtick templates and quoted strings
        chunks += literal.findall(text)

        for chunk in chunks:
            if '[[' in chunk or '${' in chunk:
                chunk = re.sub(r'\[\[.*?\]\]|\$\{.*?\}', ' ', chunk)
            for token in chunk.replace('\n', ' ').split():
                token = token.strip('\'",`{}()?:;')
                # Only strip brackets that are not part of an arbitrary value,
                # so text-[10px] survives but a stray ] does not.
                if '[' not in token:
                    token = token.strip('[]')
                if not token or not re.fullmatch(r'!?[a-z][\w:/.!\[\]#%-]*', token):
                    continue
                found.setdefault(token, set()).add(path.name)
    return found


class Command(BaseCommand):
    help = "Rebuild the CSS utilities missing from the vendored Tailwind stylesheet."

    def add_arguments(self, parser):
        parser.add_argument(
            '--check', action='store_true',
            help='Do not write. Exit non-zero if the stylesheet is stale or a class cannot be built.',
        )

    def handle(self, *args, **options):
        root = Path(settings.BASE_DIR)
        vendored = root / 'static' / 'css' / 'tailwind.css'
        if not vendored.exists():
            raise CommandError(f"Vendored stylesheet not found: {vendored}")

        css = vendored.read_text(encoding='utf-8')
        tokens = set(re.findall(r'(--(?:color|spacing|radius)-[\w-]+):', css))

        sources = sorted(
            list((root / 'dashboard' / 'templates').rglob('*.html'))
            + list((root / 'static' / 'js').glob('*.js'))
        )
        sources = [p for p in sources if p.name != 'vue.global.js']

        used = extract_classes(sources)
        compiler = Compiler(tokens)

        # Component classes are provided by hand, not generated: those compiled
        # into the vendored build from assets/css/input.css, plus static/css/
        # components.css which needs no build at all.
        provided = set()
        for stylesheet in (root / 'assets' / 'css' / 'input.css',
                           root / 'static' / 'css' / 'components.css'):
            if stylesheet.exists():
                provided |= set(re.findall(r'\.([a-zA-Z][\w-]*)', stylesheet.read_text(encoding='utf-8')))

        rules, unsupported = [], {}
        for cls in sorted(used):
            if cls in provided or cls.lstrip('!') in provided:
                continue  # hand-written component class
            if f'.{escape(cls)} {{' in css or f'.{escape(cls)}{{' in css:
                continue  # already provided by the vendored build
            rule = compiler.rule(cls)
            if rule is None:
                # Only report things that look like real utilities. Words such as
                # 'active' or 'prod' appear inside :class expressions as values.
                if re.match(r'!?(bg|text|border|ring|from|to|[pm][xytblr]?|gap|w|h)-', cls):
                    unsupported[cls] = used[cls]
                continue
            rules.append(rule)

        if unsupported:
            self.stderr.write(self.style.ERROR(
                "Cannot build these classes; extend build_css.py or use a different class:"))
            for cls, where in sorted(unsupported.items()):
                self.stderr.write(f"  {cls}   (in {', '.join(sorted(where))})")
            raise CommandError(f"{len(unsupported)} unsupported class(es)")

        content = HEADER + '\n'.join(rules) + '\n}\n'
        target = root / 'static' / GENERATED

        if options['check']:
            current = target.read_text(encoding='utf-8') if target.exists() else ''
            if current != content:
                raise CommandError(
                    f"{GENERATED} is stale. Run `python manage.py build_css` and commit the result."
                )
            self.stdout.write(self.style.SUCCESS(
                f"{GENERATED} is up to date ({len(rules)} generated utilities)."))
            return

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(
            f"Wrote {GENERATED}: {len(rules)} utilities missing from the vendored build."))
