# Generated by Django 4.2.30 on 2026-08-03 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EgressRouter',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('egress_ips', models.JSONField(blank=True, default=list)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egress_routers', to='dashboard.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('siglum', models.CharField(blank=True, max_length=100, null=True)),
                ('lifecycle', models.CharField(blank=True, max_length=50, null=True)),
                ('is_devspace', models.BooleanField(default=False)),
                ('is_cso', models.BooleanField(default=False)),
                ('devspace_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('request_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('is_decommissioned', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='dashboard.cluster')),
                ('egress_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_namespaces', to='dashboard.egressrouter')),
            ],
        ),
        migrations.CreateModel(
            name='SystemSyncStatus',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('is_syncing', models.BooleanField(default=False)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_message', models.CharField(default='Ready', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HarborConfig',
            fields=[
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='harbor_config', serialize=False, to='dashboard.namespace')),
                ('is_enabled', models.BooleanField(default=False)),
                ('storage_quota_gb', models.IntegerField(default=0)),
                ('vulnerability_scanning', models.BooleanField(default=False)),
                ('auto_sbom_generation', models.BooleanField(default=False)),
                ('cve_allowlist', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('siglum', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('is_decommissioned', models.BooleanField(default=False)),
                ('request_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='dashboard.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMeshControlPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('kiali_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_namespaces', models.JSONField(blank=True, default=list)),
                ('cp_tenant', models.CharField(blank=True, max_length=255, null=True)),
                ('dataplane_namespaces', models.JSONField(blank=True, default=list)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_service_mesh_cp', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='RouteException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('granted_at', models.DateField(blank=True, null=True)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_exception', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='RobotAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_suffix', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_accounts', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('limits_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_memory', models.CharField(blank=True, max_length=50, null=True)),
                ('limits_memory', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_ephemeral_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_quota', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_mirrors', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flows_enabled', models.BooleanField(default=False)),
                ('dns_resolution_enabled', models.BooleanField(default=False)),
                ('proxy_enabled', models.BooleanField(default=False)),
                ('s3_connection_enabled', models.BooleanField(default=False)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_policy', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pod', models.CharField(max_length=255)),
                ('to_destinations', models.JSONField(default=list)),
                ('flows', models.JSONField(default=list)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_connections', to='dashboard.namespace')),
            ],
        ),
        migrations.AddField(
            model_name='namespace',
            name='service_mesh_cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_plane_namespaces', to='dashboard.servicemeshcontrolplane'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='dashboard.tenant'),
        ),
        migrations.CreateModel(
            name='LimitRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_request_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('container_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('container_request_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('container_ram', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_min', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_max', models.CharField(blank=True, max_length=50, null=True)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit_range', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='HelmDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helm_deployments', to='dashboard.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='GPUAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_tier', models.CharField(max_length=100)),
                ('allocation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu_count', models.IntegerField(default=0)),
                ('namespace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_allocation', to='dashboard.namespace')),
            ],
        ),
        migrations.AddField(
            model_name='egressrouter',
            name='provider_namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_routers', to='dashboard.namespace'),
        ),
        migrations.CreateModel(
            name='CustomResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_resources', to='dashboard.namespace')),
            ],
        ),
    ]
