# Generated by Django 4.2.30 on 2026-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsyncstatus',
            name='sync_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
