# Generated by Django 4.2.30 on 2026-08-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systemsyncstatus_sync_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrymirror',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='registrymirror',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='resourcequota',
            name='requests_ephemeral_storage',
        ),
        migrations.RemoveField(
            model_name='servicemeshcontrolplane',
            name='cp_tenant',
        ),
        migrations.RemoveField(
            model_name='servicemeshcontrolplane',
            name='gateway_namespaces',
        ),
        migrations.RemoveField(
            model_name='servicemeshcontrolplane',
            name='kiali_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_owner',
        ),
        migrations.DeleteModel(
            name='LimitRange',
        ),
    ]
