# Generated by Django 4.2.30 on 2026-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_registrymirror_provider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpuallocation',
            name='gpu_tier',
        ),
        migrations.AddField(
            model_name='gpuallocation',
            name='limit_default',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gpuallocation',
            name='limit_default_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gpuallocation',
            name='limit_max',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gpuallocation',
            name='limit_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
