# Generated by Django 5.2.16 on 2026-08-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_gpuallocation_gpu_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeexception',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
