# Generated by Django 5.2.16 on 2026-08-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_routeexception_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('lifecycle', models.CharField(blank=True, max_length=50, null=True)),
                ('siglum', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('request_ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('is_decommissioned', models.BooleanField(default=False)),
                ('quota_enabled', models.BooleanField(default=False)),
                ('limits_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('limits_memory', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_memory', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_ephemeral_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('requests_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('harbor_enabled', models.BooleanField(default=False)),
                ('harbor_storage_quota_gb', models.IntegerField(default=0)),
                ('global_egress_ip_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='dashboard.cluster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='dashboard.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
