# Generated by Django 5.2.16 on 2026-08-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_capsule'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='capsule',
            name='owners',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='capsule',
            name='users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customresource',
            name='capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_resources', to='dashboard.capsule'),
        ),
        migrations.AlterField(
            model_name='customresource',
            name='namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_resources', to='dashboard.namespace'),
        ),
    ]
