# Generated by Django 5.2.16 on 2026-08-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_capsule_config_capsule_owners_capsule_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='capsule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='dashboard.capsule'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='dashboard.namespace'),
        ),
    ]
